### ISSUE TITLE
Gizmo with proper translation computation

### ISSUE THREAD

**Issue by florianblume** [fferri/qt3d-transform-gizmo#3]
Hey guys,

thanks for your code! I used it as inspiration for my own implementation because I wanted to correct some things like translation. In your code, the translation is off if you move too much.

So, this is the result: https://github.com/florianblume/qt3d-gizmo

Thanks again for this very good starting point, otherwise it would have taken even longer :)

Best,
Florian

**Comment by fferri** [comment]
Looks great! I think it's worth listing it on some of those "awesome qt" repos on GitHub, so it can get even more visibility.

**Comment by florianblume** [comment]
Thanks and good idea, I'll do that :)
